version: '2'
services:
  sagu:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/sagu/
    links:
      - PostgreSQL

  PostgreSQL:
    image: postgres:9.1
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - ./data:/var/lib/postgresql